# Generated by Django 5.2.1 on 2025-05-21 00:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLogsRestaurantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CIUDAD', 'Ciudad'), ('COORDENADAS', 'Coordendas')], max_length=20)),
                ('fecharegistro', models.DateTimeField(auto_now_add=True)),
                ('metadatain', models.JSONField(default=dict)),
                ('metadataout', models.JSONField(default=dict)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
